package fr.ensicaen.simulator_ep.utils;

public enum ComponentEP {
	ELETRONIC_TERMINAL_PAYMENT, ETP_CHIPSET, ETP_SMART_CARD_READER, CARD, CARD_CHIP, CARD_MAGSTRIPPE, FRONT_OFFICE, FO_ACQUIRER, FO_ACQUIRER_AUTHORIZATION, FO_ISSUER, FO_ISSUER_AUTHORIZATION, NETWORK, ROUTER, FO_ACQUIRER_REMOTE_DATA_COLLECTION
}
